# Generated by Django 5.2.3 on 2025-07-07 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('atendido', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='guiaturistico',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='ArchivoGuia',
        ),
        migrations.DeleteModel(
            name='EmpresaTuristica',
        ),
        migrations.DeleteModel(
            name='GuiaTuristico',
        ),
    ]
